# Generated by Django 5.2.9 on 2025-12-29 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_app', '0002_table_qr_image_alter_menucategory_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='no_of_tables',
            field=models.IntegerField(default=10),
        ),
    ]
